
/**
 * 所有特性的公共常量。
 */
export default class CommonConstants {
  /**
   * 输入帐号长度。
   */
  static readonly INPUT_ACCOUNT_LENGTH = 11;

  /**
   *  输入密码长度。
   */
  static readonly INPUT_PASSWORD_LENGTH = 8;

  /**
   *  输入框的左填充
   */
  static readonly INPUT_PADDING_LEFT = 0;

  /**
   * 模拟登录延迟时间
   */
  static readonly LOGIN_DELAY_TIME = 2000;

  /**
   * 元件共间距
   */
  static readonly COMMON_SPACE = 12;

  /**
   * 主页的标题文本
   */
  static readonly HOME_TITLE = '首页';

  /**
   * 设置页的标题文本
   */
  static readonly MINE_TITLE = '我的';

  /**
   * 其他登录方式的间距
   */
  static readonly LOGIN_METHODS_SPACE = 44;

  /**
   * 组件的宽度或高度分布在父组件上
   */
  static readonly FULL_PARENT = '100%';

  /**
   * 按钮的宽度
   */
  static readonly BUTTON_WIDTH = '90%';

  /**
   * 设定列表的宽度
   */
  static readonly SET_LIST_WIDTH = '42%';

  /**
   * 主标签索引
   */
  static readonly HOME_TAB_INDEX = 0;

  /**
   * 个人标签索引
   */
  static readonly MINE_TAB_INDEX = 1;
}

